name: BetterDeathScreen Build and Upload

on:
  push:
  pull_request:

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check Java and Maven versions
        run: |
          java -version
          mvn -v

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          server-id: github
          cache: 'maven'

      - name: Check Java and Maven versions
        run: |
          java -version
          mvn -v

      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean package --file pom.xml

      - name: Upload Bukkit Artifact
        uses: actions/upload-artifact@v4
        with:
          name: BetterDeathScreen-Bukkit
          path: bukkit/target/BetterDeathScreen-Bukkit.jar
